spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/ramenlog
    username: sa
    password:
    driver-class-name: org.h2.Driver

  mail:
    host: smtp.gmail.com
    port: 587
    username: jason20021001@gmail.com
    password: pxbk atbc azdd yusi
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000  # 30 * 60 * 1000 == 30분

jwt:
  secret: 20b2ce5e86f3f8cf5123ccbdd7207c67fd7cb6b740f4b9f8bc9c90e4dade5121

